### ISSUE TITLE
Build fails with Sphinx 4.1.0

### ISSUE THREAD

**Issue by atisman89** [ammaraskar/sphinx-action#31]
Hi, my GitHub Action Sphinx doc generation started failing with Sphinx 4.1.0 (It has been working with previous Sphinx 4.0.2).
The errors I got are:

```
...
Running Sphinx v4.1.0

Extension error:
Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' (/usr/local/lib/python3.8/site-packages/sphinx/deprecation.py))
make: *** [Makefile:20: html] Error 2
...
```

**Comment by robb-romans** [comment]
Same error here

**Comment by robb-romans** [comment]
Please note that builds fail even if you're not trying to build ePub format in your local `Makefile`.

**Comment by atisman89** [comment]
Adding sphinx with version 4.0.2 in my requirements.txt solves the issue. Looks like it has nothing to do with this action.

**Comment by astrojuanlu** [comment]
Sphinx 4.1.1 should have fixed the issue as well.

**Comment by robb-romans** [comment]
Thank you.
